# Generated by Django 5.1.6 on 2025-03-06 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
    ]
