# Generated by Django 5.1.6 on 2025-04-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on'], 'verbose_name': 'Commission', 'verbose_name_plural': 'Commissions'},
        ),
    ]
