# Generated by Django 5.2 on 2025-04-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_postcategory_remove_post_thread_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Post Categories'},
        ),
    ]
